name: Run CI
on: [pull_request]
jobs:

  build:
    name: Run CI
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
      id: go

    - name: Check out the code
      uses: actions/checkout@v1

    - name: Make ci
      run: make ci
